appname="拼运检查"
appver="1.0"
appcode="1"
appsdk="15"
path_pattern=""
packagename="com.androlua.demo"
theme="Theme_DeviceDefault"
app_key=""
app_channel=""
developer=""
description=""
debugmode=false
user_permission={
  "INTERNET",
  "WRITE_EXTERNAL_STORAGE"
}
